// AUTO-GENERATED by scripts/generate-content-manifest.mjs — do not edit by hand.
// Run `npm run generate:content` after adding or removing a broker JSON file.
// Source of truth: content/brokers/**/*.json

import { Broker } from './types';

import b0 from '../../content/brokers/us/beenverified.json';
import b1 from '../../content/brokers/us/spokeo.json';
import b2 from '../../content/brokers/us/whitepages.json';

// Cast at the single chokepoint: the CI content validator (lib/content/validate.mjs)
// is the real schema gate; a data-integrity unit test asserts the safety invariants.
export const BROKERS = [b0, b1, b2] as unknown as Broker[];
